type Query{
    cars: [Car],
    buses: [Bus],
    onRoadCars(state:Boolean): [Car],
    findByVisitedCountries(countries:[String!]!):[Car!],
    findBusByCapacity(capacity:Int):[Bus!]!,
    findCarByID(carID: Int):Car!,
    getCarsFromIDCache(carID: Int):Car!,
    getAllCarsFromIDCache:[Car!]!,
    getAllOwners:[Owner!]!,
    countCars:Int
}

type Mutation{
    addCar(car: CarInput): Car,
    add100cars: String,
    stopAdding100Cars:String
}

input CarInput{
    id: ID!
    name: String!
    model: Int!
    owner: OwnerInput!

}
input OwnerInput{
    id: ID!
    name: String!
    phoneNumber: String!
}

type Owner{
    id: ID!
    name: String!
    phoneNumber: String!
}

type Car{
    id: ID!
    name: String!
    model: Int!
    owner: Owner
}
type Bus{
    id: ID!
    name: String!
    model: Int!
    capacity: Int!
}